package com.filish.design.spine

import androidx.compose.runtime.Immutable
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.filish.design.Reach

/**
 * P · SPINE — the row anatomy, as production geometry.
 *
 * ===========================================================================
 * What the spine is, and is not
 * ===========================================================================
 *
 * It is a visual column GENERATED BY THE CONTENT. Each object contributes one
 * mark whose width is that object's magnitude, and the marks stack into a
 * profile of the directory that can be read in one glance.
 *
 * It is not a sidebar, not a navigation rail, not a progress indicator, not a
 * decorative line. Nothing draws it except the objects themselves, and in an
 * empty folder there is no spine at all - which is correct, because there is
 * nothing to have magnitude.
 *
 * ===========================================================================
 * Every gap here has a reason
 * ===========================================================================
 *
 * There is no uniform 8dp rhythm, for the reason set out in [com.filish.design.Space]:
 * when every gap is the same, no gap means anything, and the interface then
 * needs boxes and dividers to re-introduce the grouping that uniform spacing
 * destroyed.
 *
 *   EDGE -> SPINE      18dp. Enough that the spine reads as inside the
 *                      composition rather than clamped to the bezel.
 *   SPINE CHANNEL      26dp. Fixed, so a ragged spine never produces a ragged
 *                      text column. At 16dp the marks read as coloured tabs
 *                      stuck to rows - a borrowed labelling convention. At
 *                      26dp, detached, they read as a landscape.
 *   SPINE -> TEXT      16dp. The detachment is the point: substrate shows
 *                      between the mark and the ink, so the mark is an object
 *                      in its own right rather than a row decoration.
 *   NAME -> METADATA   3dp (Space.bond). One thing, two lines.
 *   MARK -> MARK       2dp, above and below each mark. LOAD-BEARING: without
 *                      it, runs of same-kind same-size files fuse into one
 *                      continuous bar that says "one object" about four.
 *   ROW -> ROW         0. Rows abut. Separation comes from the mark gaps and
 *                      from the text's own leading, which is what lets a run
 *                      of selected rows merge into one collective body.
 */
@Immutable
object Spine {

    /** Screen edge to the leading edge of the mark. */
    val gutter: Dp = 18.dp

    /** The fixed channel the mark lives in. */
    val channel: Dp = 26.dp

    /** Channel to the start of the text column. */
    val detach: Dp = 16.dp

    /** Where the text column always starts. Never varies with mark width. */
    val textInset: Dp = gutter + channel + detach

    /** Breathing room above and below each mark. Load-bearing - see above. */
    val markGap: Dp = 2.dp

    /**
     * Vertical padding inside a row.
     *
     * Combined with a one-line name and one metadata line this lands just
     * under the 48dp floor, so [Reach.touch] does the work; with a two-line
     * name or a large font setting the row simply grows. THE ROW HEIGHT IS
     * NEVER SPECIFIED - it is measured. See [com.filish.design.spine.ContentObject].
     */
    val rowPadding: Dp = 9.dp

    /** Trailing inset for the text column. */
    val trailing: Dp = 18.dp

    /** The floor a row may never go below, whatever the content. */
    val minHeight: Dp = Reach.touch

    /**
     * How far the mark may intrude before it stops being an edge.
     *
     * Mirrors [com.filish.design.glass.Mass.markMax] and exists so a reader of
     * this file does not have to go and find it.
     */
    val markCeiling: Dp = 26.dp
}
